swagger: "2.0"
info:
  title: Online Bazzar API with Express
  description: API for online mall.
  version: 1.0.0
schemes:
  - http

paths:
  /products:
    get:
      summary: Returns a list of products.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: Ok

  /products/{id}:
    get:
      summary: Return product by id
      parameters:
        - in: path
          name: id
          required: true
          type: string
          description: the id of the product.
      produces:
        - application/json
      responses:
        200:
          description: Ok
        500:
          description: Unknown error
